.PHONY: run-server1 run-server2
run-server1:
	@echo "run server"
	@go run cmd/v1/server/main.go

run-server2:
	@echo "run server"
	@go run cmd/v2/server/main.go

.PHONY: run-client1 run-client2
run-client1:
	@echo "run client"
	@go run cmd/v1/client/main.go

run-client2:
	@echo "run client"
	@go run cmd/v2/client/main.go